[build]
  publish = "dist"
  command = "npx rimraf package-lock.json npm-shrinkwrap.json node_modules && npm i dumi -g && npm i && npm run build:dumi"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200